sudo: required

language: node_js
node_js:
  - stable

cache:
  directories:
    - node_modules

service:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t react-docker .

script:
  - docker run react-docker yarn coverage

before_deploy:
  - npm install -g vercel
deploy:
  provider: script
  script: vercel --token $VERCEL_TOKEN --prod --yes
  on:
    branch: main
