sudo: required
servicer:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t react-docker .

script:
  - docker run react-docker yarn coverage

deploy:
  provider: script
  script: vercel --token $VERCEL_TOKEN --prod
  on:
    branch: main
